---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}/gha/{group_name}"
      prefix: "dbt"
      separator: "-"
      word-separator: "-"
      branch-name-case: "lowercase"
      max-length: 34
    commit-message:
      prefix: "fix(all): "

  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}/npm/{group_name}"
      prefix: "dbt"
      separator: "-"
      word-separator: "-"
      branch-name-case: "lowercase"
      max-length: 34
    commit-message:
      prefix: "fix(all): "

  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      template: "{prefix}/{package_manager}/{group_name}"
      prefix: "dbt"
      separator: "-"
      word-separator: "-"
      branch-name-case: "lowercase"
      max-length: 34
    commit-message:
      prefix: "fix(all): "
