---
version: 2

pull-request-branch-name:
  template: "{prefix}/{name}"
  prefix: "dbt"
  separator: "-"
  word-separator: "-"
  branch-name-case: "lowercase"
  max-length: 34
commit-message:
  prefix: "fix(all): "

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"

  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
